name: person_note
description: An app to note people who have helped you.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  go_router: ^6.0.0
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.0
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
