name: person_note
description: An app to note people who have helped you.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-444.1.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  intl: any
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.1.1
  go_router: ^6.0.0
  flutter_datetime_picker: ^1.5.1
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.3.0
  google_sign_in: ^5.4.2
  firebase_analytics: ^10.0.8
  flutter_svg: ^1.1.6
  dropdown_button2: ^1.9.2

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_gen_runner:
  flutter_launcher_icons: ^0.11.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/

flutter_gen:
  output: lib/gen/
  line_length: 80 
  integrations:
    flutter_svg: true
  
flutter_icons:
  android: "launcher_icon"
  image_path: "assets/img/app_icon.png"

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  screenshot_test: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/screenshot_test.dart -d sdk gphone64 x86 64
  gen_icon: flutter pub run flutter_launcher_icons
