name: person_note
description: An app to note people who have helped you.
publish_to: "none"

version: 1.0.1+2

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  cloud_firestore: ^4.16.0
  dropdown_button2: ^2.3.9
  firebase_analytics: ^10.10.0
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  go_router: ^13.2.2
  google_sign_in: ^6.2.1
  hooks_riverpod: ^2.5.1
  intl: ^0.19.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.9
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.0
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  pedantic_mono: ^1.26.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/img/

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true

flutter_icons:
  android: "launcher_icon"
  image_path: "assets/img/app_icon.png"

scripts:
  build: flutter pub run build_runner build --delete-conflicting-outputs
  screenshot_test: flutter drive --driver=test_driver/integration_test.dart --target=integration_test/screenshot_test.dart -d sdk gphone64 x86 64
  gen_icon: flutter pub run flutter_launcher_icons
